server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tmm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ww
    password: 1
  jpa:
    database: mysql
    show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect